In [1]:
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('USA_Housing.csv')

In [3]:
df.drop(columns=['Address'], inplace = True)

In [4]:
df

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0          79545.45857             5.682861                   7.009188   
1          79248.64245             6.002900                   6.730821   
2          61287.06718             5.865890                   8.512727   
3          63345.24005             7.188236                   5.586729   
4          59982.19723             5.040555                   7.839388   
...                ...                  ...                        ...   
4995       60567.94414             7.830362                   6.137356   
4996       78491.27543             6.999135                   6.576763   
4997       63390.68689             7.250591                   4.805081   
4998       68001.33124             5.534388                   7.130144   
4999       65510.58180             5.992305                   6.792336   

      Avg. Area Number of Bedrooms  Area Population         Price  
0                             4.09      23086.80050  1.059034e+06  
1                             3.09      40173.07217  1.505891e+06  
2                             5.13      36882.15940  1.058988e+06  
3                             3.26      34310.24283  1.260617e+06  
4                             4.23      26354.10947  6.309435e+05  
...                            ...              ...           ...  
4995                          3.46      22837.36103  1.060194e+06  
4996                          4.02      25616.11549  1.482618e+06  
4997                          2.13      33266.14549  1.030730e+06  
4998                          5.44      42625.62016  1.198657e+06  
4999                          4.07      46501.28380  1.298950e+06  

[5000 rows x 6 columns]

In [5]:
df=np.array(df.values.tolist())

In [6]:
df.shape

(5000, 6)

In [7]:
from sklearn.preprocessing import StandardScaler,normalize
scaler = StandardScaler()
X_norm = normalize(df)
print(f"Peak to Peak range by column in Raw        X:{np.ptp(df,axis=0)}")   
print(f"Peak to Peak range by column in Normalized X:{np.ptp(X_norm,axis=0)}")

Peak to Peak range by column in Raw        X:[8.99051172e+04 6.87478388e+00 7.52339432e+00 4.50000000e+00
 6.94491027e+04 2.45312694e+06]
Peak to Peak range by column in Normalized X:[8.73324453e-01 7.04466312e-05 1.31442612e-04 5.92935723e-05
 5.60659715e-01 6.94914746e-01]


In [8]:
X_norm=X_norm.reshape(6,5000)


In [9]:
X_norm

array([[7.48826896e-02, 5.34974526e-06, 6.59832590e-06, ...,
        9.98266755e-01, 4.86033889e-02, 5.67533321e-06],
       [5.20952449e-06, 2.59547663e-06, 2.36826947e-02, ...,
        4.60264952e-06, 4.75596820e-06, 3.04098958e-06],
       [3.07978526e-02, 9.98482202e-01, 4.98958926e-02, ...,
        1.43656385e-06, 3.42561106e-02, 9.98199028e-01],
       [4.49684283e-02, 3.30681254e-06, 4.77865208e-06, ...,
        9.97935489e-01, 4.17501977e-02, 3.72056855e-06],
       [3.85664391e-06, 3.07741967e-06, 1.89400307e-02, ...,
        5.09675739e-06, 5.85401291e-06, 2.86128360e-06],
       [1.99815422e-02, 9.97844865e-01, 4.46461913e-02, ...,
        3.12732334e-06, 3.57308477e-02, 9.98092913e-01]])

In [10]:
data = {'feature1': X_norm[0], 'feature2': X_norm[1], 'feature3': X_norm[2],'feature4': X_norm[3],'feature5': X_norm[4]}  
X_train = pd.DataFrame(data)

In [11]:
X_train=np.array(pd.DataFrame(data).values.tolist())
y_train=np.array(X_norm[5])

In [12]:
y_train

array([1.99815422e-02, 9.97844865e-01, 4.46461913e-02, ...,
       3.12732334e-06, 3.57308477e-02, 9.98092913e-01])

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X_train,y_train, test_size=0.33, random_state=42)
m = len(X_train)

In [14]:
# data is stored in numpy array/matrix
print(f"X Shape: {X_train.shape}, X Type:{type(X_train)})")
print(X_train)
print(f"y Shape: {y_train.shape}, y Type:{type(y_train)})")
print(y_train)

X Shape: (3350, 5), X Type:<class 'numpy.ndarray'>)
[[4.03472941e-02 6.97100713e-02 5.67485478e-06 2.66690129e-02
  1.59311273e-01]
 [3.70882880e-06 6.50733731e-06 9.98743975e-01 7.08531952e-06
  2.30178555e-06]
 [3.08309406e-02 6.81708489e-02 5.31539352e-06 2.90938898e-02
  6.24216518e-02]
 ...
 [5.91338917e-06 3.66225722e-02 5.92407980e-02 4.78280065e-06
  3.84459762e-02]
 [2.94179215e-02 3.86499289e-02 8.10027695e-06 5.86831242e-02
  6.24711891e-02]
 [5.28481198e-06 3.08186757e-02 5.06437826e-02 5.15541595e-06
  2.02403218e-02]]
y Shape: (3350,), y Type:<class 'numpy.ndarray'>)
[8.44129086e-06 9.97911893e-01 5.71787790e-06 ... 4.38713491e-02
 5.09449017e-06 1.58968886e-01]


In [15]:
b_init = 9999999999
w_init=(np.linalg.inv((X_train.T) @ X_train)@(X_train.T))@ y_train
print(f"w_init shape: {w_init.shape}, b_init type: {type(b_init)}")
w_init

w_init shape: (5,), b_init type: <class 'int'>


array([-0.00296906,  0.0094992 ,  0.99986784,  0.00300613, -0.00945214])

In [16]:
def loss(X, y, w):    
    m = X.shape[0]
    cost = 0.0
    f_wb = X @ w 
    cost = (1/(2*m)) * np.sum((f_wb-y)**2)                              
    return(np.squeeze(cost))    

In [17]:
# Compute and display cost using our pre-chosen optimal parameters. 
cost = loss(X_train, y_train, w_init)
print(f'Cost at optimal w : {cost}')

Cost at optimal w : 8.294537570500453e-05


In [18]:
def compute_gradient(X, y, w): 
    m,n = X.shape          
    dj_dw = np.zeros((n,))
    dj_db = 0.
    f_wb = X @ w             
    e   = f_wb - y                
    dj_dw  = (1/m) * (X.T @ e)    
    dj_db  = (1/m) * np.sum(e)    
    return dj_db,dj_dw

In [19]:
#Compute and display gradient 
tmp_dj_db, tmp_dj_dw = compute_gradient(X_train, y_train, w_init)
print(f'dj_db at initial w,b: {tmp_dj_db}')
print(f'dj_dw at initial w,b: \n {tmp_dj_dw}')

dj_db at initial w,b: -0.00040482765562210263
dj_dw at initial w,b: 
 [-3.63696428e-18  2.78493025e-17 -4.25307592e-17 -3.27163669e-18
  2.81340431e-17]


In [20]:
import copy,math
def gradient_descent(X, y, w_in, cost_function, gradient_function, alpha, num_iters): 
    m = len(X)
    hist={}
    hist["cost"] = []; hist["params"] = []; hist["grads"]=[]; hist["iter"]=[];
    w = copy.deepcopy(w_in)     #avoid modifying global w within function
    
    save_interval = np.ceil(num_iters/10000) # prevent resource exhaustion for long runs
    print(f"Iteration Cost          w0       w1       w2       w3       b       djdw0    djdw1    djdw2    djdw3    djdb  ")
    print(f"---------------------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|")
    for i in range(num_iters):
        dj_db,dj_dw = gradient_function(X, y, w)   
        w = w - alpha * dj_dw               
        #b = b - alpha * dj_db               
        if i == 0 or i % save_interval == 0:     
            hist["cost"].append(cost_function(X, y, w))
            hist["params"].append([w])
            hist["grads"].append([dj_dw,dj_db])
            hist["iter"].append(i)
        # Print cost every at intervals 10 times or as many iterations if < 10
        if i% math.ceil(num_iters/10) == 0:
            #print(f"Iteration {i:4d}: Cost {cost_function(X, y, w, b):8.2f}   ")
            cst = cost_function(X, y, w)
            print(f"{i:9d} {cst:0.5e} {w[0]: 0.1e} {w[1]: 0.1e} {w[2]: 0.1e} {dj_dw[0]: 0.1e} {dj_dw[1]: 0.1e} {dj_dw[2]: 0.1e} {dj_db: 0.1e}")
    return w, hist

In [21]:

initial_w = np.zeros_like(w_init)
initial_b = 1150000
iterations = 60000
alpha = 1.0e-1
# run gradient descent 
w_final, J_hist = gradient_descent(X_train, y_train, w_init,
                                                    loss, compute_gradient, 
                                                    alpha, iterations)
print(f"b,w found by gradient descent:{w_final} ")
m,_ = X_train.shape
for i in range(m):
    print(f"prediction: {np.dot(X_train[i], w_final) }, target value: {y_train[i]}")

Iteration Cost          w0       w1       w2       w3       b       djdw0    djdw1    djdw2    djdw3    djdb  
---------------------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|
        0 8.29454e-05 -3.0e-03  9.5e-03  1.0e+00 -3.6e-18  2.8e-17 -4.3e-17 -4.0e-04
     6000 8.29454e-05 -3.0e-03  9.5e-03  1.0e+00 -2.1e-18  8.2e-18 -4.3e-17 -4.0e-04
    12000 8.29454e-05 -3.0e-03  9.5e-03  1.0e+00 -2.1e-18  8.2e-18 -4.3e-17 -4.0e-04
    18000 8.29454e-05 -3.0e-03  9.5e-03  1.0e+00 -2.1e-18  8.2e-18 -4.3e-17 -4.0e-04
    24000 8.29454e-05 -3.0e-03  9.5e-03  1.0e+00 -2.1e-18  8.2e-18 -4.3e-17 -4.0e-04
    30000 8.29454e-05 -3.0e-03  9.5e-03  1.0e+00 -2.1e-18  8.2e-18 -4.3e-17 -4.0e-04
    36000 8.29454e-05 -3.0e-03  9.5e-03  1.0e+00 -2.1e-18  8.2e-18 -4.3e-17 -4.0e-04
    42000 8.29454e-05 -3.0e-03  9.5e-03  1.0e+00 -2.1e-18  8.2e-18 -4.3e-17 -4.0e-04
    48000 8.29454e-05 -3.0e-03  9.5e-03  1.0e+00 -2.1e-18  8.2e-18 -4.3e-17 -4.0e-04
    54000 8

In [22]:
w_final

array([-0.00296906,  0.0094992 ,  0.99986784,  0.00300613, -0.00945214])

In [23]:
fcost=loss(X_test,y_test,w_final)
print(f'Cost at optimal w : {fcost}')

Cost at optimal w : 0.00014316918932909834


In [24]:
y_pred=(X_test@ w_final) 

In [27]:
w_final

array([-0.00296906,  0.0094992 ,  0.99986784,  0.00300613, -0.00945214])

In [26]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
# The mean squared error
print("Mean squared error: %.9f" % mean_squared_error(y_test, y_pred))
# The absolute error
print("Absolute error: %.9f" % mean_absolute_error(y_test, y_pred))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination: %.9f" % r2_score(y_test, y_pred))

Mean squared error: 0.000286338
Absolute error: 0.005319276
Coefficient of determination: 0.997948597
