In [1]:
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

In [2]:

d = [[],[],[],[],[]] 
for i in range(1000):
    X1 = random.randint(0,100)
    d[0].append(X1)
    
    X2 = random.randint(0,100)
    d[1].append(X2)
    
    X3 = random.randint(0,100)
    d[2].append(X3)
    X4 = 1
    d[3].append(X4)
    Y = 5 * X1 + 3 * X2 + 1.5 * X3 + 6
    d[4].append(Y)

In [3]:
from sklearn.preprocessing import StandardScaler,normalize
scaler = StandardScaler()
d_norm = normalize(d)

print(f"Peak to Peak range by column in Raw        X:{np.ptp(d,axis=0)}")   
print(f"Peak to Peak range by column in Normalized X:{np.ptp(d_norm,axis=0)}")

Peak to Peak range by column in Raw        X:[175.  761.5 717.  560.  465.  416.5 818.5 228.5 326.   96.  759.  560.
 613.  380.5 303.  185.5 570.5 757.  425.5 261.5 834.  602.  682.  458.
 667.5 214.  426.  450.5 590.  694.5 331.5 670.5 277.5 574.5 636.  366.
 518.5 673.5 444.  397.  164.  705.5 630.  505.5 389.  445.  347.5 544.
 618.  397.  319.5 477.5 598.  619.  424.  402.  652.5 447.  782.5 404.5
 412.  398.  395.5 514.  206.5 669.5 241.5 486.5 398.5 383.  405.5 206.5
 387.  463.5 709.  505.  716.  303.  256.  128.5 551.5 505.5 517.5 650.5
 199.  308.5 314.5 757.5 610.5 739.  619.  623.5 526.5 639.5 221.5 452.5
 487.5 364.  317.  789.  306.5 803.  636.5 695.  789.  756.  101.  526.5
 273.  629.  562.5 508.  546.  545.5 386.5 402.  583.  442.5 482.5 711.
 503.  384.5 242.  603.  550.  288.5 732.5 490.5 444.  511.  242.5 485.5
 566.5 621.5 627.5 428.5 620.  176.5 446.5 426.5 772.5 138.  387.5 663.
 389.5 520.5 346.  608.  358.  310.  254.5 269.5 717.  343.  404.5 473.5
 427.5 569.5

In [4]:
d_norm

array([[0.00222955, 0.03734499, 0.04291887, ..., 0.01281992, 0.02173813,
        0.01449209],
       [0.00108987, 0.0512237 , 0.0479541 , ..., 0.04359464, 0.00980879,
        0.0016348 ],
       [0.05110213, 0.04950519, 0.02235718, ..., 0.01650173, 0.03247115,
        0.03779428],
       [0.03162278, 0.03162278, 0.03162278, ..., 0.03162278, 0.03162278,
        0.03162278],
       [0.01092317, 0.04732339, 0.04456157, ..., 0.02529086, 0.02150499,
        0.01560896]])

In [5]:
d_norm.shape

(5, 1000)

In [6]:
data = {'feature1': d_norm[0], 'feature2': d_norm[1], 'feature3': d_norm[2],'b': d_norm[3]}  
X_train = pd.DataFrame(data)

In [7]:
X_train=np.array(pd.DataFrame(data).values.tolist())
y_train=np.array(d_norm[4])

In [90]:
#y_train=y_train.reshape(-1, 1)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X_train,y_train, test_size=0.33, random_state=42)
m = len(X_train)

In [9]:
# data is stored in numpy array/matrix
print(f"X Shape: {X_train.shape}, X Type:{type(X_train)})")
print(X_train)
print(f"y Shape: {y_train.shape}, y Type:{type(y_train)})")
print(y_train)

X Shape: (670, 4), X Type:<class 'numpy.ndarray'>)
[[0.03177111 0.01471319 0.04152048 0.03162278]
 [0.05239447 0.02561185 0.03566503 0.03162278]
 [0.00836082 0.05176863 0.00053231 0.03162278]
 ...
 [0.00055739 0.00708413 0.00319388 0.03162278]
 [0.04124671 0.01362332 0.03140652 0.03162278]
 [0.03511544 0.04304971 0.02821263 0.03162278]]
y Shape: (670,), y Type:<class 'numpy.ndarray'>)
[0.03034904 0.04453054 0.02280832 0.04499601 0.01092317 0.01368499
 0.02029475 0.02193944 0.01123349 0.01269198 0.0077269  0.01846388
 0.02153602 0.01796737 0.04934046 0.04102395 0.0387276  0.02578737
 0.03847935 0.02044991 0.02330483 0.03078348 0.04254451 0.02383237
 0.03556237 0.03019388 0.047913   0.02600459 0.03069038 0.02423578
 0.02069817 0.03435213 0.02665626 0.0270907  0.0484095  0.03667951
 0.02426682 0.01145071 0.02820785 0.02178428 0.0304111  0.02858023
 0.04800609 0.02820785 0.05086101 0.03835522 0.02026372 0.02882848
 0.03348324 0.01666404 0.05318839 0.0323661  0.02321174 0.04642347
 0.042854

In [93]:
#y_train=y_train.reshape(670,)

In [10]:

w_init=np.linalg.inv((X_train.T) @ X_train)@(X_train.T)@ y_train
print(f"w_init shape: {w_init.shape}")
w_init

w_init shape: (4,)


array([0.5567349 , 0.34167578, 0.1748878 , 0.01177572])

In [11]:
def loss(X, y, w):    
    m = X.shape[0]
    cost = 0.0
    f_wb = X @ w  
    cost = (1/(2*m)) * np.sum((f_wb-y)**2)                              
    return(np.squeeze(cost))    

In [12]:
# Compute and display cost using our pre-chosen optimal parameters. 
cost = loss(X_train, y_train, w_init)
print(f'Cost at optimal w : {cost}')

Cost at optimal w : 2.3210813182089673e-34


In [13]:
def compute_gradient(X, y, w): 
    m,n = X.shape          
    dj_dw = np.zeros((n,))
    dj_db = 0.
    f_wb = X @ w              
    e   = f_wb - y                
    dj_dw  = (1/m) * (X.T @ e)    
    dj_db  = (1/m) * np.sum(e)    
    return dj_db,dj_dw

In [14]:
#Compute and display gradient 
tmp_dj_db, tmp_dj_dw = compute_gradient(X_train, y_train, w_init)
print(f'dj_db at initial w,b: {tmp_dj_db}')
print(f'dj_dw at initial w,b: \n {tmp_dj_dw}')

dj_db at initial w,b: -4.029995657250598e-18
dj_dw at initial w,b: 
 [ 4.88176116e-20  1.25481884e-19  7.01879876e-20 -1.27439652e-19]


In [15]:
import copy,math
def gradient_descent(X, y, w_in, cost_function, compute_gradient, alpha, num_iters): 
    m = len(X)
    hist={}
    hist["cost"] = []; hist["params"] = []; hist["grads"]=[]; hist["iter"]=[];
    w = copy.deepcopy(w_in)     #avoid modifying global w within function
    
    save_interval = np.ceil(num_iters/10000) # prevent resource exhaustion for long runs
    print(f"Iteration Cost          w0       w1       w2       w3       b       djdw0    djdw1    djdw2    djdw3    djdb  ")
    print(f"---------------------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|")
    for i in range(num_iters):
        dj_db,dj_dw = compute_gradient(X, y, w)   
        w = w - alpha * dj_dw               
        #b = b - alpha * dj_db               
        if i == 0 or i % save_interval == 0:     
            hist["cost"].append(cost_function(X, y, w))
            hist["params"].append([w])
            hist["grads"].append([dj_dw,dj_db])
            hist["iter"].append(i)
        # Print cost every at intervals 10 times or as many iterations if < 10
        if i% math.ceil(num_iters/10) == 0:
            #print(f"Iteration {i:4d}: Cost {cost_function(X, y, w, b):8.2f}   ")
            cst = cost_function(X, y, w)
            print(f"{i:9d} {cst:0.5e} {w[0]: 0.1e} {w[1]: 0.1e} {w[2]: 0.1e}  {dj_dw[0]: 0.1e} {dj_dw[1]: 0.1e} {dj_dw[2]: 0.1e} {dj_db: 0.1e}")
    return w, hist

In [16]:

initial_w = np.zeros_like(w_init)
initial_b = 800
iterations = 5000
alpha = 5.0e-7
# run gradient descent 
w_final, J_hist = gradient_descent(X_train, y_train, w_init,
                                                    loss, compute_gradient, 
                                                    alpha, iterations)
print(f"b,w found by gradient descent: {w_final} ")
m,_ = X_train.shape
for i in range(m):
    print(f"prediction: {np.dot(X_train[i], w_final) }, target value: {y_train[i]}")

Iteration Cost          w0       w1       w2       w3       b       djdw0    djdw1    djdw2    djdw3    djdb  
---------------------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|
        0 2.32108e-34  5.6e-01  3.4e-01  1.7e-01   4.9e-20  1.3e-19  7.0e-20 -4.0e-18
      500 2.32108e-34  5.6e-01  3.4e-01  1.7e-01   4.9e-20  1.3e-19  7.0e-20 -4.0e-18
     1000 2.32108e-34  5.6e-01  3.4e-01  1.7e-01   4.9e-20  1.3e-19  7.0e-20 -4.0e-18
     1500 2.32108e-34  5.6e-01  3.4e-01  1.7e-01   4.9e-20  1.3e-19  7.0e-20 -4.0e-18
     2000 2.32108e-34  5.6e-01  3.4e-01  1.7e-01   4.9e-20  1.3e-19  7.0e-20 -4.0e-18
     2500 2.32108e-34  5.6e-01  3.4e-01  1.7e-01   4.9e-20  1.3e-19  7.0e-20 -4.0e-18
     3000 2.32108e-34  5.6e-01  3.4e-01  1.7e-01   4.9e-20  1.3e-19  7.0e-20 -4.0e-18
     3500 2.32108e-34  5.6e-01  3.4e-01  1.7e-01   4.9e-20  1.3e-19  7.0e-20 -4.0e-18
     4000 2.32108e-34  5.6e-01  3.4e-01  1.7e-01   4.9e-20  1.3e-19  7.0e-20 -4.0e-18
  

In [17]:
w_final

array([0.5567349 , 0.34167578, 0.1748878 , 0.01177572])

In [18]:
fcost=loss(X_test,y_test,w_final)
print(f'Cost at optimal w : {fcost}')

Cost at optimal w : 2.428089732325418e-34


In [19]:
y_pred=(X_test@ w_final)

In [32]:
w_final

array([0.5567349 , 0.34167578, 0.1748878 , 0.01177572])

In [31]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
# The mean squared error
print("Mean squared error: %.50f" % mean_squared_error(y_test, y_pred))
# The absolute error
print("Absolute error: %.50f" % mean_absolute_error(y_test, y_pred))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination: %.40f" % r2_score(y_test, y_pred))

Mean squared error: 0.00000000000000000000000000000000048561794646508364
Absolute error: 0.00000000000000001786239506475512259850882670138322
Coefficient of determination: 1.0000000000000000000000000000000000000000
